name: Deploy GitHub Pages
on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: bash build.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
